"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

const initial = { firstName: "", lastName: "", email: "", phone: "", city: "", province: "", cuit: "", taxCategory: "", commercialExperience: "", commercialApproach: "", hasMonotributo: false, consentConfirmed: false, independentRelationshipAcknowledged: false, monotributoAcknowledged: false };

export default function AdvisorRegistrationPage() {
  const [form, setForm] = useState(initial);
  const [state, setState] = useState<"idle" | "sending" | "done" | "error">("idle");
  const [message, setMessage] = useState("");
  const update = (key: keyof typeof initial, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setState("sending"); setMessage("");
    const response = await fetch("/api/public/advisors/apply", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) });
    const payload = await response.json().catch(() => ({}));
    if (!response.ok) { setState("error"); setMessage(payload.error || "No pudimos enviar la solicitud."); return; }
    setState("done");
  }
  if (state === "done") return <main className="min-h-screen bg-[#06101d] px-6 py-32 text-white"><div className="mx-auto max-w-2xl rounded-3xl border border-sky-300/20 bg-white/[0.06] p-10"><p className="text-sm uppercase tracking-[0.25em] text-orange-300">Solicitud enviada</p><h1 className="mt-4 text-4xl font-semibold">Estamos revisando tu alta como Asesor/a Opturon.</h1><p className="mt-5 leading-7 text-slate-300">Recibimos tus datos. El acceso al Portal del Asesor queda reservado para solicitudes aprobadas. Te contactaremos por email si necesitamos información adicional.</p><Link className="mt-8 inline-block rounded-xl border border-white/20 px-5 py-3 font-semibold" href="/asesores">Volver al programa</Link></div></main>;
  return <main className="min-h-screen bg-[#06101d] px-6 py-24 text-white sm:px-10"><div className="mx-auto max-w-3xl"><Link href="/asesores" className="text-sm text-sky-300">← Programa de asesores</Link><p className="mt-10 text-sm uppercase tracking-[0.25em] text-orange-300">Postulación pública</p><h1 className="mt-4 text-5xl font-semibold tracking-tight">Quiero ser asesor/a</h1><p className="mt-4 max-w-2xl leading-7 text-slate-300">Completá tus datos. El programa funciona bajo una relación comercial independiente y requiere Monotributo para operar y facturar.</p><form onSubmit={submit} className="mt-10 grid gap-5 rounded-3xl border border-white/10 bg-white/[0.05] p-6 sm:grid-cols-2 sm:p-8">{([["firstName","Nombre"],["lastName","Apellido"],["email","Email"],["phone","Teléfono"],["city","Localidad"],["province","Provincia"],["cuit","CUIT"],["taxCategory","Categoría fiscal"]] as const).map(([key,label]) => <label key={key} className="grid gap-2 text-sm text-slate-200">{label}<input required={!["taxCategory"].includes(key)} value={String(form[key])} onChange={(e) => update(key,e.target.value)} className="rounded-xl border border-white/15 bg-slate-950/60 px-4 py-3 text-white outline-none focus:border-sky-300" /></label>)}<label className="grid gap-2 text-sm text-slate-200 sm:col-span-2">Experiencia comercial / ventas<textarea required value={form.commercialExperience} onChange={(e) => update("commercialExperience",e.target.value)} className="min-h-24 rounded-xl border border-white/15 bg-slate-950/60 px-4 py-3 text-white" /></label><label className="grid gap-2 text-sm text-slate-200 sm:col-span-2">¿Cómo pensás trabajar comercialmente con Opturon?<textarea value={form.commercialApproach} onChange={(e) => update("commercialApproach",e.target.value)} className="min-h-24 rounded-xl border border-white/15 bg-slate-950/60 px-4 py-3 text-white" /></label><div className="grid gap-3 text-sm text-slate-300 sm:col-span-2">{([["hasMonotributo","Cuento actualmente con Monotributo"],["consentConfirmed","Acepto los términos del Programa de Asesores y la política de privacidad"],["independentRelationshipAcknowledged","Comprendo que se trata de una relación comercial independiente"],["monotributoAcknowledged","Comprendo que Monotributo es requisito para operar y facturar"]] as const).map(([key,label]) => <label key={key} className="flex gap-3"><input type="checkbox" checked={Boolean(form[key])} onChange={(e) => update(key,e.target.checked)} />{label}</label>)}</div>{message && <p className="sm:col-span-2 text-sm text-red-300">{message}</p>}<button disabled={state === "sending"} className="sm:col-span-2 rounded-xl bg-orange-400 px-5 py-3 font-bold text-slate-950 disabled:opacity-50">{state === "sending" ? "Enviando…" : "Enviar solicitud"}</button></form></div></main>;
}
